export const types = {
    // User types
    SET_AUTHENTICATED: 'SET_AUTHENTICATED',
    SET_UNAUTHENTICATED: 'SET_UNAUTHENTICATED',
    SET_USER: 'SET_USER',
    LOADING_USER: 'LOADING_USER',
    // UI types
    SET_ERRORS: 'SET_ERRORS',
    LOADING_UI: 'LOADING_UI',
    CLEAR_ERRORS: 'CLEAR_ERRORS',
    GET_ALL_REQUESTS: 'GET_ALL_REQUESTS',
    GET_USER_REQUESTS: 'GET_USER_REQUESTS',
    TOGGLE_CHECKBOX: 'TOGGLE_CHECKBOX'
}